### ISSUE TITLE
Fails for too large modules (i.e. azure-sdk-for-go)

### ISSUE THREAD

**Issue by roessland** [oligot/go-mod-upgrade#27] opened 2022-05-24 10:29 UTC
Recently azure-sdk-for-go [became too large for `go get`](https://github.com/Azure/azure-sdk-for-go/issues/18209) which causes a bunch of problems. v64.1.0 is the latest version below the size limit, and v64.2.0 is the latest version.

```
go-mod-upgrade     
   ⨯ upgrade failed            error=Error running go command to discover modules: exit status 1 stderr=go: loading module retractions for github.com/Azure/azure-sdk-for-go@v64.1.0+incompatible: verifying go.mod: github.com/Azure/azure-sdk-for-go@v64.2.0+incompatible/go.mod: reading https://sum.golang.org/lookup/github.com/!azure/azure-sdk-for-go@v64.2.0+incompatible: 410 Gone
        server response: not found: create zip: module source tree too large (max size is 524288000 bytes)
```

It would be nice if go-mod-upgrade kept working and was able to update the other (non-broken) modules.

**Comment by oligot** [comment] 2022-05-25 09:59
Hi,

Unfortunately, I can't reproduce this bug as azure-sdk-for-go v65.0.0 has been released in the meantime and the actual bug has been resolved in this version.

According to [this comment](https://github.com/Azure/azure-sdk-for-go/issues/18209#issuecomment-1135258128), you could use the environment variable GONOSUMDB as a workaround so, this *should* also work with go-mod-upgrade (note that I haven't tested it).

But I agree with you that go-mod-upgrade could in this case ignore the broken modules and allow to update the other modules.
PR are always welcomed :smirk:

**Comment by oligot** [comment] 2022-12-17 11:25
Closing this issue following the thumb up emoji.
Feel free to reopen if needed.

**Closed by oligot** 2022-12-17 11:25 UTC
